charts/hivemq-operator/Chart.yaml, charts/hivemq-operator/crds/hivemq-cluster.yaml, charts/hivemq-operator/operator-tmpls/cluster-daemon-set.yaml, charts/hivemq-operator/operator-tmpls/cluster-deployment.yaml, charts/hivemq-operator/operator-tmpls/cluster-stateful-set.yaml, charts/hivemq-operator/templates/hivemq-operator/custom-resource.yaml, charts/hivemq-operator/values.yaml
NOTE: merging this will result in immediate release.
** DO NOT MERGE UNTIL OPERATOR & HIVEMQ DOCKER IMAGES HAVE BEEN RELEASED **
=> default extension / REST API support

charts/hivemq-operator/Chart.yaml, charts/hivemq-operator/operator-tmpls/cluster-daemon-set.yaml, charts/hivemq-operator/operator-tmpls/cluster-deployment.yaml, charts/hivemq-operator/operator-tmpls/cluster-stateful-set.yaml, charts/hivemq-operator/values.yaml
must only be merged after release
=> operator-template updates: dns-init container

CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE, README.md
add contributing, code of conduct and license file
=> improve readmes

charts/hivemq-operator/Chart.yaml, charts/hivemq-operator/README.md, charts/hivemq-operator/crds/hivemq-cluster.yaml, charts/hivemq-operator/operator-tmpls/cluster-daemon-set.yaml, charts/hivemq-operator/operator-tmpls/cluster-deployment.yaml, charts/hivemq-operator/operator-tmpls/cluster-stateful-set.yaml, charts/hivemq-operator/operator-tmpls/service-monitor.yaml, charts/hivemq-operator/templates/global/hivemq-clusterrole.yaml, charts/hivemq-operator/templates/global/hivemq-psp.yaml, charts/hivemq-operator/templates/hivemq-operator/admission-webhooks/job-patch/psp.yaml, charts/hivemq-operator/templates/hivemq-operator/custom-resource.yaml, charts/hivemq-operator/templates/hivemq-operator/operator-cluster-role.yaml, charts/hivemq-operator/templates/hivemq-operator/operator-deployment.yaml, charts/hivemq-operator/values.yaml, manifests/legacy/v1beta1-hivemq-cluster.yaml, manifests/operator/hivemq-clusterrole.yaml, manifests/operator/hivemq-psp.yaml, manifests/operator/operator-cluster-role.yaml, manifests/operator/operator-deployment.yaml, manifests/operator/operator-templates.yaml
still a WIP, dependent images still pending release/update
=> Run HiveMQ & operator as non-root user by default

charts/hivemq-operator/Chart.yaml, charts/hivemq-operator/values.yaml, charts/hivemq-swarm/Chart.yaml, charts/hivemq-swarm/values.yaml
merge this after 4.6.4 release
=> [don't merge] version up to 4.6.4

charts/hivemq-operator/CHANGELOG.md, charts/hivemq-operator/Chart.yaml, charts/hivemq-operator/README.md, charts/hivemq-operator/crds/hivemq-cluster.yaml, charts/hivemq-operator/operator-tmpls/cluster-daemon-set.yaml, charts/hivemq-operator/operator-tmpls/cluster-deployment.yaml, charts/hivemq-operator/operator-tmpls/cluster-stateful-set.yaml, charts/hivemq-operator/operator-tmpls/service-monitor.yaml, charts/hivemq-operator/templates/global/hivemq-clusterrole.yaml, charts/hivemq-operator/templates/global/hivemq-psp.yaml, charts/hivemq-operator/templates/hivemq-operator/admission-webhooks/job-patch/psp.yaml, charts/hivemq-operator/templates/hivemq-operator/custom-resource.yaml, charts/hivemq-operator/templates/hivemq-operator/operator-cluster-role.yaml, charts/hivemq-operator/templates/hivemq-operator/operator-deployment.yaml, charts/hivemq-operator/values.yaml, charts/hivemq-swarm/Chart.yaml, charts/hivemq-swarm/values.yaml, manifests/legacy/v1beta1-hivemq-cluster.yaml, manifests/operator/hivemq-clusterrole.yaml, manifests/operator/hivemq-psp.yaml, manifests/operator/operator-cluster-role.yaml, manifests/operator/operator-deployment.yaml, manifests/operator/operator-templates.yaml
these changes currently have pre-release status and must not be released
after releasing 4.6.4 (except for the helm chart), merge #28 into this one first and then merge this PR.
=> [don't merge] incoming 4.6.4 changes

charts/hivemq-operator/CHANGELOG.md, charts/hivemq-operator/Chart.yaml, charts/hivemq-operator/README.md, charts/hivemq-operator/crds/hivemq-cluster.yaml, charts/hivemq-operator/operator-tmpls/cluster-daemon-set.yaml, charts/hivemq-operator/operator-tmpls/cluster-deployment.yaml, charts/hivemq-operator/operator-tmpls/cluster-stateful-set.yaml, charts/hivemq-operator/operator-tmpls/service-monitor.yaml, charts/hivemq-operator/templates/global/hivemq-clusterrole.yaml, charts/hivemq-operator/templates/global/hivemq-psp.yaml, charts/hivemq-operator/templates/hivemq-operator/admission-webhooks/job-patch/psp.yaml, charts/hivemq-operator/templates/hivemq-operator/custom-resource.yaml, charts/hivemq-operator/templates/hivemq-operator/operator-cluster-role.yaml, charts/hivemq-operator/templates/hivemq-operator/operator-deployment.yaml, charts/hivemq-operator/values.yaml, charts/hivemq-swarm/Chart.yaml, charts/hivemq-swarm/values.yaml, manifests/legacy/v1beta1-hivemq-cluster.yaml, manifests/operator/hivemq-clusterrole.yaml, manifests/operator/hivemq-psp.yaml, manifests/operator/operator-cluster-role.yaml, manifests/operator/operator-deployment.yaml, manifests/operator/operator-templates.yaml
Bumped all versions as necessary
=> Release 4.7.0

charts/hivemq-operator/CHANGELOG.md, charts/hivemq-operator/Chart.yaml, charts/hivemq-operator/values.yaml
https://github.com/jet/kube-webhook-certgen/issues/30
=> fix: change webhook for the upstream nginx version

charts/hivemq-operator/values.yaml
=> Corrected HIVEMQ_MAX_CONNECTIONS applying for max-connections

charts/hivemq-swarm/README.md
Fixes issue https://github.com/hivemq/helm-charts/issues/72
=> Fix broken links on Readme

charts/hivemq-operator/Chart.yaml, charts/hivemq-operator/crds/hivemq-cluster.yaml, charts/hivemq-operator/values.yaml, manifests/legacy/v1beta1-hivemq-cluster.yaml
=> update the crd to remove empty properties

charts/hivemq-operator/CHANGELOG.md
missed the changelog entry in #75.
=> doc: add missing changelog entry

charts/hivemq-operator/Chart.lock, charts/hivemq-operator/Chart.yaml
https://hivemq.kanbanize.com/ctrl_board/22/cards/13288/details/
=> fix: Upgrade kube-prometheus-stack to version: 30.*

charts/hivemq-operator/Chart.yaml, charts/hivemq-operator/values.yaml, charts/hivemq-swarm/Chart.yaml, charts/hivemq-swarm/values.yaml
https://hivemq.kanbanize.com/ctrl_board/41/cards/14141/details/
=> Update version to 4.16.0

charts/hivemq-operator/Chart.yaml
https://hivemq.kanbanize.com/ctrl_board/22/cards/16721/details/
=> change Chart.yaml description

index.md
Fix up the descriptions of the public facing helm-charts page and the links.
=> fix public facing helm-chart repo page

charts/hivemq-platform-operator/crds/hivemq-platforms.hivemq.com-v1.yml
https://hivemq.kanbanize.com/ctrl_board/22/cards/17449/details/
=> Publish CRD for HiveMQ Platform Operator 1.1.0

build.gradle.kts
https://hivemq.kanbanize.com/ctrl_board/22/cards/18241/details/
=> Renaming from `version` to `appVersion` parameter when bumping helm charts.

README.md, charts/hivemq-platform-operator/templates/deployment.yml, charts/hivemq-platform-operator/tests/custom-env-vars-values.yaml, charts/hivemq-platform-operator/tests/hivemq_operator_deployment_test.yaml, charts/hivemq-platform-operator/values.schema.json, charts/hivemq-platform-operator/values.yaml, charts/hivemq-platform/templates/hivemq-custom-resource.yml, charts/hivemq-platform/tests/custom-env-vars-values.yaml, charts/hivemq-platform/tests/hivemq_platform_test.yaml, charts/hivemq-platform/values.schema.json, charts/hivemq-platform/values.yaml, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/single/HelmCustomConfigIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/testcontainer/HelmChartContainer.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/testcontainer/LogWaiterUtil.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/util/K8sUtil.java, tests-hivemq-platform-operator/src/integrationTest/resources/operator-custom-env-var-config-map.yml, tests-hivemq-platform-operator/src/integrationTest/resources/values/custom-operator-env-vars-test-values.yaml, tests-hivemq-platform-operator/src/integrationTest/resources/values/custom-platform-env-vars-test-values.yaml
https://hivemq.kanbanize.com/ctrl_board/22/cards/18402/details/
=> Include support for EnvVars in both Platform and Operator charts.

charts/hivemq-platform/templates/NOTES.txt, charts/hivemq-platform/templates/_helpers.tpl, charts/hivemq-platform/templates/hivemq-configuration.yml, charts/hivemq-platform/tests/hivemq_configuration_test.yaml, charts/hivemq-platform/values.schema.json, charts/hivemq-platform/values.yaml, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/single/HelmRestApiIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/testcontainer/HelmChartContainer.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/util/K8sUtil.java, tests-hivemq-platform-operator/src/integrationTest/resources/ese-config-map.yml, tests-hivemq-platform-operator/src/integrationTest/resources/ese-file-realm-config-map.yml, tests-hivemq-platform-operator/src/integrationTest/resources/hivemq-config-map-update.yml, tests-hivemq-platform-operator/src/integrationTest/resources/hivemq-config-map.yml, tests-hivemq-platform-operator/src/integrationTest/resources/values/hivemq-config-override.xml, tests-hivemq-platform-operator/src/integrationTest/resources/values/rest-api-test-values.yaml, tests-hivemq-platform-operator/src/integrationTest/resources/values/rest-api-test-with-auth-values.yaml
https://hivemq.kanbanize.com/ctrl_board/22/cards/18607/details/
=> Make REST API authentication configurable

charts/hivemq-platform/templates/tests/test-mqtt-cli.yml, manifests/hivemq-operator/manifests.sh, manifests/hivemq-swarm/manifests.sh, tests-hivemq-operator/build.gradle.kts, tests-hivemq-operator/gradle.properties, tests-hivemq-platform-operator/build.gradle.kts
https://hivemq.kanbanize.com/ctrl_board/22/cards/19142/details/
=> Fix Version Updates when releasing

charts/hivemq-platform-operator/templates/rbac.yml, charts/hivemq-platform/templates/hivemq-custom-resource.yml, charts/hivemq-platform/tests/hivemq_platform_test.yaml, charts/hivemq-platform/values.schema.json, charts/hivemq-platform/values.yaml, manifests/hivemq-platform-operator/rbac.yml, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/single/HelmCustomServiceAccountIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/util/K8sUtil.java
https://hivemq.kanbanize.com/ctrl_board/22/cards/19401/details/
=> Add missing clusterroles permission for Platform Operator account and include support for custom service account

charts/hivemq-platform/templates/hivemq-custom-resource.yml, charts/hivemq-platform/tests/hivemq_platform_test.yaml, charts/hivemq-platform/values.schema.json, charts/hivemq-platform/values.yaml, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/AbstractHelmChartIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/single/HelmInitContainerIT.java, tests-hivemq-platform-operator/src/integrationTest/resources/values/init-container-additional-volumes-test-values.yaml, tests-hivemq-platform-operator/src/integrationTest/resources/values/init-containers-spec.yaml
Add option to configure InitContainers without having to override the StatefulSet
https://hivemq.kanbanize.com/ctrl_board/22/cards/16443/details/
=> Add option to configure specific InitContainers

charts/hivemq-platform-operator/crds/hivemq-platforms.hivemq.com-v1.yml
https://hivemq.kanbanize.com/ctrl_board/22/cards/19365/details/
=> Improve Init App update

charts/hivemq-platform-operator/crds/hivemq-platforms.hivemq.com-v1.yml
https://hivemq.kanbanize.com/ctrl_board/22/cards/19632/details/
=> Publish CRD for HiveMQ Platform Operator 1.2.0

charts/hivemq-platform-operator/Chart.yaml, charts/hivemq-platform-operator/values.yaml, charts/hivemq-platform/Chart.yaml, manifests/hivemq-platform-operator/deployment.yml, manifests/hivemq-platform-operator/rbac.yml, manifests/hivemq-platform-operator/service-account.yml, manifests/hivemq-platform-operator/service.yml
https://hivemq.kanbanize.com/ctrl_board/22/cards/19861/details/
=> Release HiveMQ Platform Operator 1.2.0

.github/workflows/hivemq-operator-integration-test.yml, .github/workflows/hivemq-platform-operator-integration-test.yml, .github/workflows/smoke-test.yml, charts/hivemq-platform-operator/crds/hivemq-platforms.hivemq.com-v1.yml, tests-hivemq-operator/README.md, tests-hivemq-operator/build.gradle.kts, tests-hivemq-platform-operator/README.md, tests-hivemq-platform-operator/build.gradle.kts, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/Version.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/extensions/AppendingBarPublishInboundInterceptorExtensionMain.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/extensions/AppendingBazPublishInboundInterceptorExtensionMain.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/extensions/AppendingFooPublishInboundInterceptorExtensionMain.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/extensions/AppendingPublishInboundInterceptor.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/extensions/BaseAppendingPublishInboundInterceptorExtensionMain.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/extensions/CustomTestExtensionMain.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/single/HelmPlatformMutualTlsIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/util/HiveMQExtension.java
https://hivemq.kanbanize.com/ctrl_board/22/cards/19539/details/
=> Switch project to Java 21

charts/hivemq-platform-operator/templates/bindings.yml, charts/hivemq-platform-operator/templates/rbac.yml, manifests/hivemq-platform-operator/bindings.yml, manifests/hivemq-platform-operator/rbac.yml, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/Chart.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/Version.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/single/HelmApplyCrdIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/testcontainer/HelmChartContainer.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/testcontainer/LogWaiterUtil.java
https://hivemq.kanbanize.com/ctrl_board/22/cards/19972/details/
=> Add permissions to create and update CRDs

examples/hivemq-operator/localStatefulTest.yml, tests-hivemq-operator/src/integrationTest/resources/values/ese-extension-values.yaml, tests-hivemq-operator/src/integrationTest/resources/values/log-extension-values.yaml, tests-hivemq-operator/src/integrationTest/resources/values/permissions-values.yaml, tests-hivemq-operator/src/integrationTest/resources/values/stateful-set-values.yaml, tests-hivemq-operator/src/integrationTest/resources/values/test-values.yaml, tests-hivemq-operator/src/integrationTest/resources/values/update-stateful-set-values.yaml
https://hivemq.kanbanize.com/ctrl_board/22/cards/20699/details/
=> Remove memory configuration for integration tests

manifests/hivemq-operator/manifests.sh, manifests/hivemq-platform-operator/manifests.sh, manifests/hivemq-platform/manifests.sh, manifests/hivemq-swarm/manifests.sh
=> Include missing Prometheus Helm Chart repo to the manifest scripts

.github/workflows/hivemq-operator-integration-test.yml, .github/workflows/hivemq-platform-operator-integration-test.yml, .github/workflows/release.yaml, .github/workflows/release.yml, .github/workflows/smoke-test.yml, .github/workflows/verify.yml, .gitignore, tests-hivemq-operator/src/integrationTest/java/com/hivemq/helmcharts/EseExtensionInstallationIT.java, tests-hivemq-operator/src/integrationTest/java/com/hivemq/helmcharts/ExtensionInstallationIT.java, tests-hivemq-operator/src/integrationTest/java/com/hivemq/helmcharts/LocalHelmChartDeploymentIT.java, tests-hivemq-operator/src/integrationTest/java/com/hivemq/helmcharts/StatefulSetRollingUpgradeIT.java, tests-hivemq-operator/src/integrationTest/java/com/hivemq/helmcharts/UserPermissionsIT.java, tests-hivemq-operator/src/integrationTest/java/com/hivemq/helmcharts/testcontainer/DockerImageNames.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/testcontainer/DockerImageNames.java
* Update `DockerImageNames`
* Add missing names in GitHub actions
* Update Helm setup in GitHub actions
* Add `prometheus-community` to `verify` GitHub action to resolve linter warning
* Cleanup `.gitignore`
=> Small Helm chart improvements

charts/hivemq-platform-operator/Chart.yaml, charts/hivemq-platform-operator/values.yaml, manifests/hivemq-platform-operator/deployment.yml, manifests/hivemq-platform-operator/rbac.yml, manifests/hivemq-platform-operator/service-account.yml, manifests/hivemq-platform-operator/service.yml
https://hivemq.kanbanize.com/ctrl_board/22/cards/22108/details/
=> Release HiveMQ Platform Operator 1.3.1

charts/hivemq-platform-operator/crds/hivemq-platforms.hivemq.com-v1.yml
https://hivemq.kanbanize.com/ctrl_board/22/cards/21156/details/
=> Publish CRD for HiveMQ Platform Operator 1.4.0

charts/hivemq-platform/templates/_helpers.tpl, charts/hivemq-platform/templates/hivemq-custom-resource.yml, charts/hivemq-platform/tests/additional-volumes-values.yaml, charts/hivemq-platform/tests/hivemq_platform_test.yaml, charts/hivemq-platform/tests/sidecar-container-values.yaml, charts/hivemq-platform/values.schema.json, charts/hivemq-platform/values.yaml, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/single/HelmSidecarContainerIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/testcontainer/HelmChartContainer.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/testcontainer/K3sLogConsumer.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/util/K8sUtil.java, tests-hivemq-platform-operator/src/integrationTest/resources/consul-template-config-map.yml, tests-hivemq-platform-operator/src/integrationTest/resources/values/mock-license.lic, tests-hivemq-platform-operator/src/integrationTest/resources/values/sidecar-containers-test-values.yaml
https://hivemq.kanbanize.com/ctrl_board/22/cards/22061/details/
=> Add Sidecar containers support

.github/workflows/hivemq-operator-integration-test.yml, .github/workflows/hivemq-platform-operator-integration-test.yml, .github/workflows/smoke-test.yml, .github/workflows/verify.yml
Could be further improved using a composite action:
https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
https://github.blog/changelog/2021-08-25-github-actions-reduce-duplication-with-action-composition/
=> Improve GitHub actions

.github/workflows/hivemq-operator-integration-test.yml, .github/workflows/hivemq-platform-operator-integration-test.yml, .github/workflows/smoke-test.yml, build.gradle.kts
https://hivemq.kanbanize.com/ctrl_board/22/cards/22118/details/
=> Fix operator branch checkout

.github/workflows/hivemq-platform-operator-integration-test.yml, charts/hivemq-platform/templates/_helpers.tpl, charts/hivemq-platform/templates/hivemq-custom-resource.yml, charts/hivemq-platform/tests/hivemq_platform_test.yaml, charts/hivemq-platform/values.schema.json, charts/hivemq-platform/values.yaml, tests-hivemq-platform-operator/build.gradle.kts, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/compose/HelmUpgradeExtensionIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/single/HelmAdditionalVolumesIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/single/HelmPodSecurityContextUpgradePlatformIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/single/HelmVolumeClaimTemplatesIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/testcontainer/HelmChartContainer.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/util/K8sUtil.java, tests-hivemq-platform-operator/src/integrationTest/resources/values/volumes-claim-templates-test-values.yaml
https://hivemq.kanbanize.com/ctrl_board/22/cards/22008/details/
=> Added VolumeClaimTemplates support for HiveMQ Platform chart

.github/workflows/hivemq-operator-integration-test.yml, .github/workflows/hivemq-platform-operator-integration-test.yml, .github/workflows/smoke-test.yml, renovate.json5, tests-hivemq-operator/build.gradle.kts, tests-hivemq-platform-operator/build.gradle.kts
https://hivemq.kanbanize.com/ctrl_board/41/cards/22846/details/
=> Use GitHub org secrets

charts/hivemq-platform-operator/crds/hivemq-platforms.hivemq.com-v1.yml, charts/hivemq-platform-operator/templates/rbac.yml, charts/hivemq-platform-operator/tests/hivemq_operator_rbac_test.yaml
https://hivemq.kanbanize.com/ctrl_board/22/cards/22001/details/
=> Remove unnecessary permissions if ServiceAccount and permissions creation and validation is disabled

tests-hivemq-operator/gradle/libs.versions.toml, tests-hivemq-platform-operator/gradle/libs.versions.toml
https://dc-square.slack.com/archives/C0450GFJ0KV/p1719569475654579
=> Add junit-jupiter library to properly trigger Renovate updates

.gitignore, charts/hivemq-platform-operator/crds/hivemq-platforms.hivemq.com-v1.yml, examples/hivemq-platform/manifest-customization/README.md, examples/hivemq-platform/manifest-customization/add-proxy-protocol.sh, examples/hivemq-platform/manifest-customization/create-manifests.sh, examples/hivemq-platform/manifest-customization/install.sh, examples/hivemq-platform/manifest-customization/uninstall.sh, examples/hivemq-platform/manifest-customization/values.yaml
https://hivemq.kanbanize.com/ctrl_board/22/cards/23433/details/
=> Support secrets as configuration parameter for extensions

tests-hivemq-platform-operator/src/integrationTest/resources/values/disable-bridge-test-values.yaml
https://hivemq.kanbanize.com/ctrl_board/22/cards/24285/details/
=> Fix HelmUpgradeExtensionIT.withBridgeConfiguration_enableDisableBridge() to disable the extension instead of removing it

charts/hivemq-platform-operator/crds/hivemq-platforms.hivemq.com-v1.yml
https://hivemq.kanbanize.com/ctrl_board/22/cards/16658/details/
=> Add support for StatefulSet migration

charts/hivemq-platform-operator/crds/hivemq-platforms.hivemq.com-v1.yml
https://hivemq.kanbanize.com/ctrl_board/22/cards/24285/details/
=> Add new StatePhase INVALID_VOLUME_CLAIM_TEMPLATES

charts/hivemq-platform/values.yaml
https://hivemq.kanbanize.com/ctrl_board/22/cards/24779/details/
=> Document podSecurityContext requirements for volumeClaimTemplates

charts/hivemq-platform-operator/Chart.yaml, charts/hivemq-platform-operator/values.yaml, charts/hivemq-platform/Chart.yaml, charts/hivemq-platform/values.yaml, manifests/hivemq-platform-operator/bindings.yml, manifests/hivemq-platform-operator/deployment.yml, manifests/hivemq-platform-operator/rbac.yml, manifests/hivemq-platform-operator/service-account.yml, manifests/hivemq-platform-operator/service.yml
https://hivemq.kanbanize.com/ctrl_board/22/cards/25041/details/
=> Release HiveMQ Platform Operator 1.5.1

charts/hivemq-platform/templates/hivemq-configuration.yml, charts/hivemq-platform/tests/hivemq_configuration_test.yaml, charts/hivemq-platform/values.schema.json, charts/hivemq-platform/values.yaml, tests-hivemq-operator/src/integrationTest/java/com/hivemq/helmcharts/util/JUnitUtil.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/AbstractHelmChartIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/AbstractHelmPodSecurityContextIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/single/HelmCustomLogbackIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/util/JUnitUtil.java, tests-hivemq-platform-operator/src/integrationTest/resources/values/custom-logback.xml
https://hivemq.kanbanize.com/ctrl_board/22/cards/24584/details/
=> Add support for custom logback.xml and tracing.xml

charts/hivemq-platform-operator/Chart.yaml, charts/hivemq-platform-operator/values.yaml, charts/hivemq-platform/Chart.yaml, charts/hivemq-platform/values.yaml, manifests/hivemq-platform-operator/bindings.yml, manifests/hivemq-platform-operator/deployment.yml, manifests/hivemq-platform-operator/rbac.yml, manifests/hivemq-platform-operator/service-account.yml, manifests/hivemq-platform-operator/service.yml, manifests/manifests-common.sh, tests-hivemq-platform-operator/build.gradle.kts, tests-hivemq-platform-operator/gradle/libs.versions.toml, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/single/HelmControlCenterIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/testcontainer/DockerImageNames.java
https://hivemq.kanbanize.com/ctrl_board/22/cards/25419/details/
=> Release HiveMQ Platform Operator 1.5.2

tests-hivemq-platform-operator/gradle/libs.versions.toml, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/testcontainer/DockerImageNames.java
https://hivemq.kanbanize.com/ctrl_board/22/cards/25659/details/
=> Small improvements

charts/hivemq-platform-operator/crds/hivemq-platforms.hivemq.com-v1.yml
https://hivemq.kanbanize.com/ctrl_board/22/cards/25444/details/
=> Publish CRD for HiveMQ Platform Operator 1.6.0

charts/hivemq-platform-operator/tests/hivemq_operator_deployment_test.yaml, charts/hivemq-platform-operator/values.yaml, charts/hivemq-platform/tests/hivemq_platform_test.yaml, charts/hivemq-platform/values.yaml, examples/hivemq-platform/platform-non-root-values.yml, manifests/hivemq-platform-operator/deployment.yml, manifests/hivemq-platform/hivemq-custom-resource.yml
https://hivemq.kanbanize.com/ctrl_board/22/cards/25820/details/
=> Change default CPU resource to 1000m in both Platform and Platform Operator charts

charts/hivemq-swarm/files/grafana-dashboard.json, charts/hivemq-swarm/templates/NOTES.txt, charts/hivemq-swarm/templates/_helpers.tpl, charts/hivemq-swarm/templates/configmap_grafana_dashboard.yaml, charts/hivemq-swarm/templates/servicemonitor.yaml, charts/hivemq-swarm/tests/configmap_grafana_dashboard_test.yaml, charts/hivemq-swarm/tests/release_notes_test.yaml, charts/hivemq-swarm/tests/servicemonitor_test.yaml, charts/hivemq-swarm/values.schema.json, charts/hivemq-swarm/values.yaml
https://hivemq.kanbanize.com/ctrl_board/22/cards/22656/details/
=> Restore previous ServiceMonitor and Grafana dashboard ConfigMap templates and values

charts/hivemq-platform-operator/templates/_helpers.tpl, charts/hivemq-platform-operator/templates/service.yml, charts/hivemq-platform-operator/tests/hivemq_operator_deployment_test.yaml, charts/hivemq-platform-operator/tests/hivemq_operator_rbac_test.yaml, charts/hivemq-platform-operator/tests/hivemq_operator_release_notes_test.yaml, charts/hivemq-platform-operator/tests/hivemq_operator_service_test.yaml, charts/hivemq-platform-operator/tests/hivemq_operator_tls_test.yaml, charts/hivemq-platform/templates/_helpers.tpl, charts/hivemq-platform/tests/hivemq_configuration_test.yaml, charts/hivemq-platform/tests/hivemq_platform_release_notes_test.yaml, charts/hivemq-platform/tests/hivemq_platform_test.yaml
https://hivemq.kanbanize.com/ctrl_board/22/cards/25897/details/
=> Fix Service not being created when service account is disabled

charts/hivemq-platform/templates/_config-xml.tpl, charts/hivemq-platform/tests/configuration/configmap/hivemq_configuration_test.yaml, charts/hivemq-platform/tests/configuration/secret/hivemq_configuration_test.yaml, charts/hivemq-platform/values.schema.json
https://hivemq.kanbanize.com/ctrl_board/22/cards/27019/details/
=> HiveMQ Internal Options support

charts/hivemq-platform-operator/templates/deployment.yml, charts/hivemq-platform-operator/tests/hivemq_operator_deployment_test.yaml, charts/hivemq-platform-operator/tests/hivemq_operator_tls_test.yaml, manifests/hivemq-platform-operator/deployment.yml, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/single/CustomOperatorSelectorIT.java
https://hivemq.kanbanize.com/ctrl_board/22/cards/27101/details/
=> Fix environment variables with dotted names for HiveMQ Platform Operator

charts/hivemq-platform/templates/_config-xml.tpl, charts/hivemq-platform/templates/_helpers.tpl, charts/hivemq-platform/tests/configuration/configmap/hivemq_configuration_test.yaml, charts/hivemq-platform/tests/configuration/secret/hivemq_configuration_test.yaml, charts/hivemq-platform/values.schema.json, charts/hivemq-platform/values.yaml
https://hivemq.kanbanize.com/ctrl_board/22/cards/24006/details/
=> Client Event History configuration support

.github/kubeconform.yml, .github/openapi2jsonschema.py, .github/workflows/verify.yml
https://hivemq.kanbanize.com/ctrl_board/22/cards/26132/details/
=> Add Kubeconform plugin to GitHub workflow

.github/workflows/hivemq-operator-integration-test.yml, .github/workflows/hivemq-platform-operator-integration-test.yml, charts/hivemq-operator/README.md, charts/hivemq-platform-operator/README.md, charts/hivemq-platform/README.md, charts/hivemq-platform/templates/_config-xml.tpl, charts/hivemq-platform/templates/_helpers.tpl, charts/hivemq-platform/tests/configuration/configmap/hivemq_configuration_test.yaml, charts/hivemq-platform/tests/configuration/secret/hivemq_configuration_test.yaml, charts/hivemq-platform/values.schema.json, charts/hivemq-platform/values.yaml, charts/hivemq-swarm/README.md, manifests/hivemq-operator/README.md, manifests/hivemq-operator/manifests.sh, manifests/hivemq-platform-operator/README.md, manifests/hivemq-platform-operator/manifests.sh, manifests/hivemq-platform/README.md, manifests/hivemq-platform/manifests.sh, manifests/hivemq-swarm/README.md, manifests/hivemq-swarm/manifests.sh, manifests/manifests-common.sh
https://hivemq.kanbanize.com/ctrl_board/22/cards/27402/details/
=> Add missing HiveMQ configuration options

.github/workflows/hivemq-platform-operator-integration-test.yml, charts/hivemq-platform-operator/templates/deployment.yml, charts/hivemq-platform-operator/tests/hivemq_operator_deployment_test.yaml, charts/hivemq-platform-operator/values.schema.json, charts/hivemq-platform-operator/values.yaml, charts/hivemq-platform/templates/hivemq-custom-resource.yml, charts/hivemq-platform/tests/hivemq_platform_test.yaml, charts/hivemq-platform/values.schema.json, charts/hivemq-platform/values.yaml, tests-hivemq-platform-operator/build.gradle.kts, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/AbstractHelmChartIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/compose/HelmContainerSecurityContextUpgradeExtensionIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/compose/HelmLegacyStatefulSetMigrationIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/compose/HelmPodSecurityContextUpgradeExtensionIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/single/CustomOperatorNamespacesIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/single/CustomOperatorSelectorIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/single/CustomOperatorSelectorsIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/single/HelmAdditionalContainersIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/single/HelmCustomConfigIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/single/HelmExtensionLicensesIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/single/HelmInitContainerIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/util/K8sUtil.java
https://hivemq.kanbanize.com/ctrl_board/22/cards/23369/details/
=> Add namespace configuration support

renovate.json5
https://hivemq.kanbanize.com/ctrl_board/22/cards/27627/details/
=> Switch to develop branching

renovate.json5
https://hivemq.kanbanize.com/ctrl_board/41/cards/27543/details/
=> Add team label

.github/workflows/release.yml
See https://github.com/hivemq/helm-charts/actions/runs/12030624427
=> Fix wrong working-directory for release notes updater in release workflow

charts/hivemq-platform-operator/templates/deployment.yml, charts/hivemq-platform-operator/values.schema.json, manifests/hivemq-platform-operator/deployment.yml, tests-hivemq-platform-operator/build.gradle.kts
https://hivemq.kanbanize.com/ctrl_board/22/cards/28731/details/
=> Remove Quarkus

charts/hivemq-platform-operator/files/grafana-dashboard.json, charts/hivemq-platform-operator/tests/__snapshot__/hivemq_operator_configmap_dashboard_test.yaml.snap
https://hivemq.kanbanize.com/ctrl_board/22/cards/13826/details/
=> Update Grafana dashboard for HiveMQ Platform Operator

charts/hivemq-platform-operator/templates/deployment.yml, charts/hivemq-platform-operator/templates/service-monitor.yml, charts/hivemq-platform-operator/tests/hivemq_operator_deployment_test.yaml, charts/hivemq-platform-operator/tests/hivemq_operator_service_monitor_test.yaml, charts/hivemq-platform-operator/tests/hivemq_operator_tls_test.yaml, manifests/hivemq-platform-operator/deployment.yml, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/single/HelmCustomConfigIT.java, tests-hivemq-platform-operator/src/integrationTest/resources/values/custom-operator-env-vars-values.yaml
https://hivemq.kanbanize.com/ctrl_board/22/cards/29289/details/
=> Add HiveMQ property names for Quarkus configuration properties

charts/hivemq-platform/values.yaml
https://hivemq.kanbanize.com/ctrl_board/22/cards/28888/details/
=> Reword description regarding isLicenseBase64Encoded

renovate.json5, tests-hivemq-operator/src/integrationTest/java/com/hivemq/helmcharts/CompatibilityHelmChartDeploymentIT.java, tests-hivemq-operator/src/integrationTest/java/com/hivemq/helmcharts/EseExtensionInstallationIT.java, tests-hivemq-operator/src/integrationTest/java/com/hivemq/helmcharts/ExtensionInstallationIT.java, tests-hivemq-operator/src/integrationTest/java/com/hivemq/helmcharts/LocalHelmChartDeploymentIT.java, tests-hivemq-operator/src/integrationTest/java/com/hivemq/helmcharts/StatefulSetRollingUpgradeIT.java, tests-hivemq-operator/src/integrationTest/java/com/hivemq/helmcharts/UserPermissionsIT.java, tests-hivemq-operator/src/integrationTest/java/com/hivemq/helmcharts/testcontainer/DockerImageNames.java, tests-hivemq-operator/src/integrationTest/java/com/hivemq/helmcharts/testcontainer/OperatorHelmChartContainer.java, tests-hivemq-operator/src/integrationTest/resources/helm.dockerfile, tests-hivemq-platform-operator/build.gradle.kts, tests-hivemq-platform-operator/gradle/docker.versions.toml, tests-hivemq-platform-operator/gradle/libs.versions.toml, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/compose/HelmLegacyStatefulSetMigrationIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/testcontainer/DockerImageNames.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/testcontainer/HelmChartContainer.java, tests-hivemq-platform-operator/src/integrationTest/resources/helm.dockerfile
https://hivemq.kanbanize.com/ctrl_board/22/cards/29625/details/
=> Add Renovate support for programmatic Docker images

github-release-note-updater/src/main/java/com/hivemq/release/GitHubReleaseNotesUpdater.java
https://hivemq.kanbanize.com/ctrl_board/22/cards/29665/details/
The hivemq-edge Helm chart will always be released on its own, so we don't need a complex lookup to which release blog post it needs to link to. We can just always link to the according HiveMQ Edge release blog post.
The only thing that needs to be tested is if the `appVersion` contains the version in the expected format, if the `Version` class we use can parse the YYYY.MM format correctly and put the two numbers into major and minor version as I assumed it in the code.
=> Add HiveMQ Edge to release note updater

.github/workflows/hivemq-operator-integration-test.yml, .github/workflows/hivemq-platform-operator-integration-test.yml, release/validate-branch-protection.sh, tests-hivemq-operator/build.gradle.kts, tests-hivemq-operator/gradle/docker.versions.toml, tests-hivemq-operator/gradle/libs.versions.toml, tests-hivemq-operator/src/integrationTest/java/com/hivemq/helmcharts/testcontainer/DockerImageNames.java, tests-hivemq-platform-operator/build.gradle.kts, tests-hivemq-platform-operator/gradle/docker.versions.toml, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/compose/HelmLegacyStatefulSetMigrationIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/compose/HelmUpgradeExtensionIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/single/HelmInitContainerIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/single/HelmVolumeClaimTemplatesIT.java
https://hivemq.kanbanize.com/ctrl_board/22/cards/29641/details/
=> Add matrix test for minimum and latest K8s version

charts/hivemq-platform-operator/templates/_helpers-rbac.tpl, charts/hivemq-platform-operator/templates/bindings.yml, charts/hivemq-platform-operator/templates/rbac.yml, charts/hivemq-platform-operator/tests/__snapshot__/hivemq_operator_rbac_test.yaml.snap, charts/hivemq-platform-operator/tests/__snapshot__/hivemq_operator_role_binding_test.yaml.snap, charts/hivemq-platform-operator/tests/hivemq_operator_cluster_role_binding_test.yaml, charts/hivemq-platform-operator/tests/hivemq_operator_rbac_test.yaml, charts/hivemq-platform-operator/tests/hivemq_operator_role_binding_test.yaml, manifests/hivemq-platform-operator/rbac.yml, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/platform/HelmPlatformMutualTlsIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/platform/UpdateLogLevelIT.java
https://hivemq.kanbanize.com/ctrl_board/22/cards/27640/details/
=> Create Roles and RoleBindings instead of ClusterRoles and ClusterRoleBindings for the HiveMQ Platform Operator if namespaces are configured

charts/hivemq-platform/templates/_config-xml.tpl, charts/hivemq-platform/templates/_helpers.tpl, charts/hivemq-platform/tests/configuration/configmap/hivemq_mqtt_listeners_configuration_test.yaml, charts/hivemq-platform/tests/configuration/configmap/hivemq_websocket_listeners_configuration_test.yaml, charts/hivemq-platform/tests/configuration/secret/hivemq_mqtt_listeners_configuration_test.yaml, charts/hivemq-platform/tests/configuration/secret/hivemq_websocket_listeners_configuration_test.yaml, charts/hivemq-platform/tests/services/hivemq_control_center_services_test.yaml, charts/hivemq-platform/tests/services/hivemq_metrics_services_test.yaml, charts/hivemq-platform/tests/services/hivemq_rest_api_services_test.yaml, charts/hivemq-platform/tests/services/hivemq_secure_services_test.yaml, charts/hivemq-platform/tests/tls-mqtt-services-values.yaml, charts/hivemq-platform/tests/tls-ws-services-values.yaml, charts/hivemq-platform/values.schema.json, charts/hivemq-platform/values.yaml
https://hivemq.kanbanize.com/ctrl_board/22/cards/29825/details/
=> Support HiveMQ Connect Overload Protection

.github/workflows/smoke-test.yml, charts/hivemq-edge/Chart.yaml, charts/hivemq-edge/values.yaml, manifests/hivemq-edge/configmap-configuration.yml, manifests/hivemq-edge/configmap-topicfilters.yml, manifests/hivemq-edge/secret-admin.yml, manifests/hivemq-edge/service.yml, manifests/hivemq-edge/statefulset.yml
https://hivemq.kanbanize.com/ctrl_board/57/cards/31129/details/
=> Release HiveMQ Edge 2025.4

.github/workflows/hivemq-operator-integration-test.yml, .github/workflows/hivemq-platform-operator-integration-test.yml, tests-hivemq-operator/build.gradle.kts, tests-hivemq-platform-operator/build.gradle.kts
https://hivemq.kanbanize.com/ctrl_board/22/cards/31173/details/
=> Optimize Gradle cache in integration test workflow

charts/hivemq-platform-operator/crds/hivemq-platforms.hivemq.com-v1.yml, tests-hivemq-operator/gradle/libs.versions.toml, tests-hivemq-platform-operator/gradle/libs.versions.toml
https://hivemq.kanbanize.com/ctrl_board/22/cards/28990/details/
=> Update CRD with latest version

.github/workflows/smoke-test.yml, tests-hivemq-operator/build.gradle.kts, tests-hivemq-platform-operator/build.gradle.kts, tests-hivemq-platform-operator/gradle/libs.versions.toml, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/testcontainer/HelmChartContainer.java
https://hivemq.kanbanize.com/ctrl_board/22/cards/30389/details/
=> Use Gradle Oci

charts/hivemq-platform/templates/_config-xml.tpl, charts/hivemq-platform/templates/_helpers.tpl, charts/hivemq-platform/tests/configuration/configmap/hivemq_configuration_test.yaml, charts/hivemq-platform/tests/configuration/secret/hivemq_configuration_test.yaml, charts/hivemq-platform/values.schema.json, charts/hivemq-platform/values.yaml
https://hivemq.kanbanize.com/ctrl_board/22/cards/31238/details/
=> Add HiveMQ Cluster Failure Detection to HiveMQ Platform chart

charts/hivemq-platform-operator/crds/hivemq-platforms.hivemq.com-v1.yml
https://hivemq.kanbanize.com/ctrl_board/22/cards/31839/details/
=> Add Health Status to custom resource status

charts/hivemq-platform/templates/hivemq-custom-resource.yml, charts/hivemq-platform/tests/hivemq_platform_test.yaml, manifests/hivemq-platform/hivemq-custom-resource.yml
https://hivemq.kanbanize.com/ctrl_board/22/cards/32259/details/
=> Quote StatefulSet spec resources

charts/hivemq-edge/Chart.yaml, charts/hivemq-edge/test/localdhtesting/README.md, charts/hivemq-edge/values.yaml, manifests/hivemq-edge/configmap-configuration.yml, manifests/hivemq-edge/configmap-topicfilters.yml, manifests/hivemq-edge/secret-admin.yml, manifests/hivemq-edge/service.yml, manifests/hivemq-edge/statefulset.yml
=> Release HiveMQ Edge 2025.7

charts/hivemq-platform-operator/crds/hivemq-platforms.hivemq.com-v1.yml
See https://github.com/hivemq/hivemq-platform-operator/pull/579
=> Update CRD for 1.8.0

charts/hivemq-swarm/templates/deployment_agents.yaml, charts/hivemq-swarm/templates/statefulset_commander.yaml, charts/hivemq-swarm/values.schema.json, charts/hivemq-swarm/values.yaml
https://hivemq.kanbanize.com/ctrl_board/22/cards/31798/details/
=> Add init containers support for HiveMQ Swarm Helm chart

charts/hivemq-platform/Chart.yaml, charts/hivemq-platform/templates/_config-xml.tpl, charts/hivemq-platform/templates/_helpers.tpl, charts/hivemq-platform/tests/configuration/configmap/hivemq_mqtt_listeners_configuration_test.yaml, charts/hivemq-platform/tests/configuration/configmap/hivemq_websocket_listeners_configuration_test.yaml, charts/hivemq-platform/tests/configuration/secret/hivemq_websocket_listeners_configuration_test.yaml, charts/hivemq-platform/tests/services/hivemq_control_center_services_test.yaml, charts/hivemq-platform/tests/services/hivemq_metrics_services_test.yaml, charts/hivemq-platform/tests/services/hivemq_rest_api_services_test.yaml, charts/hivemq-platform/tests/tls-ws-services-values.yaml, charts/hivemq-platform/values.schema.json, charts/hivemq-platform/values.yaml, scripts/helm-unittest.sh
https://hivemq.kanbanize.com/ctrl_board/22/cards/32954/details/
=> Make WebSocket path configurable

charts/hivemq-platform-operator/templates/service-account.yml, charts/hivemq-platform-operator/tests/hivemq_operator_service_account_test.yaml, charts/hivemq-platform-operator/values.schema.json, charts/hivemq-platform-operator/values.yaml
https://hivemq.kanbanize.com/ctrl_board/22/cards/33184/details/
=> Add configuration option for custom annotations in the ServiceAccount

charts/hivemq-platform/Chart.yaml, charts/hivemq-platform/templates/_helpers.tpl, charts/hivemq-platform/templates/hivemq-custom-resource.yml, charts/hivemq-platform/tests/services/hivemq_services_test.yaml, charts/hivemq-platform/values.schema.json, charts/hivemq-platform/values.yaml
https://hivemq.kanbanize.com/ctrl_board/22/cards/35231/details/
=> Add `nodePort` as a new HiveMQ service configuration option

tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/migration/HelmLegacyStatefulSetMigrationIT.java
https://hivemq.kanbanize.com/ctrl_board/22/cards/35914/details/
=> Adapt HelmLegacyStatefulSetMigrationIT to new metadata inheritance

.github/actions/checkout-repo/action.yml, .github/workflows/dispatcher.yml, .github/workflows/harbor.yml, .github/workflows/legacy-integration-tests.yml, .github/workflows/legacy-smoke-test.yml, .github/workflows/platform-integration-tests.yml, .github/workflows/platform-smoke-test.yml, .github/workflows/sync-branches.yml, charts/hivemq-platform/README.md, renovate.json5, tests-hivemq-operator/gradle/libs.versions.toml, tests-hivemq-operator/src/integrationTest/resources/helm.dockerfile, tests-hivemq-platform-operator/gradle/libs.versions.toml, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/migration/HelmLegacyStatefulSetMigrationIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/platform/HelmRollingUpgradePlatformIT.java, tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/testcontainer/HelmChartContainer.java
https://hivemq.kanbanize.com/ctrl_board/22/cards/36410/details/
=> Refactor GitHub workflows and switch to `next-operator-release` branch
