README.md
charts/hivemq-operator/Chart.lock
charts/hivemq-operator/Chart.yaml

so we don't break with the depreciation of the original helm stable repo

Update prometheus operator Helm repo reference, add ArtifactHub badge

---

charts/hivemq-operator/CHANGELOG.md
charts/hivemq-operator/Chart.yaml
charts/hivemq-operator/operator-tmpls/cluster-deployment.yaml

single-line env values had a trailing newline in them when rendered, this fixes that issue by using the appropriate YAML block scalar syntax

Fix env value templating

---

charts/hivemq-operator/CHANGELOG.md
charts/hivemq-operator/Chart.yaml
charts/hivemq-operator/operator-tmpls/cluster-deployment.yaml
manifests/operator/operator-templates.yaml

heapdumps are still created in the incorrect directory at the moment.

fix heapdump path

---

charts/hivemq-operator/templates/hivemq-operator/admission-webhooks/job-patch/job-createSecret.yaml
charts/hivemq-operator/templates/hivemq-operator/admission-webhooks/job-patch/job-patchWebhook.yaml
charts/hivemq-operator/templates/hivemq-operator/operator-cluster-role.yaml
charts/hivemq-operator/values.yaml
manifests/operator/operator-cluster-role.yaml
manifests/operator/operator-deployment.yaml

- Issues with pod security policies for the initial hooks:
When trying to deploy the helm chart on Openshift (with default configuration) the following issues occured:
<details><summary> kubectl describe job ...</summary>  
```
pods "hivemq-hivemq-operator-admission-create-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, spec.containers[0].securityContext.runAsUser: Invalid value: 2000: must be in the ranges: [1000620000, 1000629999], provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": …
```

fix: rootless mode on openshift (securityContext and RBAC)

---

charts/hivemq-operator/values.yaml

Have a valid default configuration  for the helm chart
Fixes the overload protection configuration - according to [our documentation](https://www.hivemq.com/docs/hivemq/4.6/user-guide/overload-protection.html) the overload protection needs to be defined in the `<hivemq></hivemq>` tag and not in `<cluster></cluster>`

fix: default configuration to enable overload protection

---

charts/hivemq-operator/templates/hivemq-operator/custom-resource.yaml
charts/hivemq-operator/values.yaml

Some customers require to use images from a trusted registry (or a pull through registry) i.e. artifactory.
The operator and the the hivemq cluster CRD already has the `initBusyboxImage` and `initDnsWaitImage` parameters for this scenario.
When using the helm-charts, the default value for these fields was not yet exposed

fix: allow to specify initBusyboxImage and initDnsWaitImage for default hivemq cluster

---

charts/hivemq-operator/CHANGELOG.md
charts/hivemq-operator/Chart.yaml
charts/hivemq-operator/values.yaml
manifests/operator/operator-deployment.yaml

Updates to current operator version which contains a bugfix and bumps the HiveMQ version to 4.7.1 as well.

Chore: update operator and HiveMQ to 4.7.1

---

charts/hivemq-operator/Chart.yaml
charts/hivemq-operator/templates/hivemq-operator/custom-resource.yaml
charts/hivemq-operator/values.yaml

the custom resource template is missing the volumeClaimTemplates field, which is necessary for statefulset resources

Add missing claim templates field in CR

---

charts/hivemq-operator/CHANGELOG.md
charts/hivemq-operator/templates/hivemq-operator/operator-deployment.yaml
charts/hivemq-operator/values.yaml

Using `affinity` helps to schedule pods in kubernetes cluster (see also: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity ).
The change adds `affinity` to the hivemq-operator to be able to perform advanced scheduling (i.e. on specific nodegroups in specific regions/zones)

Add affinity for HiveMQ operator deployment

---

charts/hivemq-operator/CHANGELOG.md
charts/hivemq-operator/Chart.yaml
charts/hivemq-operator/templates/hivemq-operator/operator-deployment.yaml
charts/hivemq-operator/values.yaml

We want to pass custom env variables to the operator when deploying via the helm chart
Adds a variable to the helm-chart operator section and renders respective keys into the deployment

Allow to pass additional environment variables 

---

charts/hivemq-operator/Chart.yaml
charts/hivemq-operator/values.yaml

- Add new enterprise extensions into the values as they are preinstalled
- hivemq-google-cloud-pubsub-extension
- hivemq-distributed-tracing-extension
- Bump operator version with multi-namespace fix

chore: Add new enterprise extensions

---

build.gradle.kts

https://hivemq.kanbanize.com/ctrl_board/22/cards/16953/details/
We have to move the instructions into a `doLast` block, otherwise they are already executed on the task registration and then replace versions with unspecified values.

Fix version update Gradle tasks

---

.github/workflows/hivemq-operator-integration-test.yml
.github/workflows/hivemq-platform-operator-integration-test.yml
.github/workflows/smoke-test.yml

Resolves the following deprecation warnings:
* https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#the-action-gradlegradle-build-action-has-been-replaced-by-gradleactionssetup-gradle
* https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#using-the-action-to-execute-gradle-via-the-arguments-parameter-is-deprecated

Fix deprecated usage of gradle/gradle-build-action

---

charts/hivemq-platform-operator/templates/NOTES.txt
charts/hivemq-platform-operator/templates/deployment.yml
charts/hivemq-platform-operator/templates/rbac.yml
charts/hivemq-platform-operator/tests/hivemq_operator_deployment_test.yaml
charts/hivemq-platform-operator/tests/hivemq_operator_rbac_test.yaml
charts/hivemq-platform-operator/tests/hivemq_operator_release_notes_test.yaml
charts/hivemq-platform-operator/values.schema.json
charts/hivemq-platform-operator/values.yaml
manifests/hivemq-platform-operator/deployment.yml
manifests/hivemq-platform-operator/rbac.yml
tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/single/HelmCustomServiceAccountIT.java

https://hivemq.kanbanize.com/ctrl_board/22/cards/22118/details/

Replace ClusterRole from Helm chart with dependent Role to allow Pod annotation updates when the operator is not running

---

charts/hivemq-platform-operator/templates/bindings.yml
charts/hivemq-platform-operator/templates/deployment.yml
charts/hivemq-platform-operator/templates/service-account.yml
charts/hivemq-platform-operator/templates/service.yml
manifests/hivemq-platform-operator/bindings.yml
manifests/hivemq-platform-operator/deployment.yml
manifests/hivemq-platform-operator/service-account.yml
manifests/hivemq-platform-operator/service.yml
tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/single/HelmCustomServiceAccountIT.java

https://hivemq.kanbanize.com/ctrl_board/22/cards/16653/details/

Add test for disabled ServiceAccount and permissions

---

charts/hivemq-platform-operator/templates/deployment.yml
charts/hivemq-platform-operator/tests/hivemq_operator_deployment_test.yaml
charts/hivemq-platform-operator/values.schema.json
charts/hivemq-platform-operator/values.yaml
charts/hivemq-platform/templates/hivemq-custom-resource.yml
charts/hivemq-platform/tests/hivemq_platform_test.yaml
charts/hivemq-platform/tests/hivemq_services_test.yaml
charts/hivemq-platform/values.schema.json
charts/hivemq-platform/values.yaml
manifests/hivemq-platform-operator/deployment.yml

https://hivemq.kanbanize.com/ctrl_board/22/cards/22802/details/
Example CR when all annotations and labels are set:
```yaml
---
apiVersion: hivemq.com/v1
kind: HiveMQPlatform
metadata:
name: "my-platform"
annotations:
global-annotation-key-1: value # <--- not configurable via Helm chart
global-annotation-key-2: value # <--- not configurable via Helm chart
labels:
app.kubernetes.io/name: "hivemq-platform"
app.kubernetes.io/instance: "my-platform"
app.kubernetes.io/version: "4.30.0"
global-label-key-1: value # <--- not configurable via Helm chart
global-label-key-2: value # <--- not configurable via Helm chart
spec:
configMapName: hivemq-configuration-my-platform
logLevel: INFO
operatorRestApiPort: 7979
healthApiPort: 8889
metricsPort: 9399
metricsPath: /
statefulSet:
spec:
replicas: 2 …
```

Support custom labels for the HiveMQ Platform

---

charts/hivemq-platform/Chart.yaml

https://hivemq.kanbanize.com/ctrl_board/22/cards/23888/details/
Added the missing version bump on the `hivemq-platform` Helm chart.

Release HiveMQ Platform Operator 1.5.0

---

.github/workflows/hivemq-platform-operator-integration-test.yml
tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/AbstractHelmChartIT.java
tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/AbstractHelmPodSecurityContextIT.java
tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/compose/HelmBridgeExtensionIT.java
tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/compose/HelmCustomExtensionIT.java
tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/compose/HelmExtensionPriorityIT.java
tests-hivemq-platform-operator/src/integrationTest/java/com/hivemq/helmcharts/compose/HelmUpgradeExtensionIT.java

We are failing to run integration tests as we fail to pull out container images when running out space in the GitHub runners.
For that, I just redistributed some of the failing tests such as `Extensions` tests for the compose GitHub workflow to reduce space disk usage and clean up containers and snapshots in the K3s container for all of the tests. This change is making the GitHub checks to not be fulfilled for this PR.

Fix tests disk space in GitHub

---

charts/hivemq-swarm/templates/NOTES.txt

https://hivemq.kanbanize.com/ctrl_board/22/cards/22656/details/

Add warning message when using deprecated Swarm `monitoring` values

---

.github/workflows/verify.yml

Latest version of Helm unittest plugin breaks our unit tests as the `equalRaw` assertion is not working properly.
See issue opened: https://github.com/helm-unittest/helm-unittest/issues/431 for the same.

Fixed Helm unittest to latest stable version 0.6.1

---

charts/hivemq-platform/templates/_helpers.tpl
charts/hivemq-platform/templates/hivemq-custom-resource.yml
charts/hivemq-platform/tests/configuration/configmap/hivemq_control_center_listeners_configuration_test.yaml
charts/hivemq-platform/tests/configuration/configmap/hivemq_rest_api_listeners_configuration_test.yaml
charts/hivemq-platform/tests/configuration/configmap/hivemq_websocket_listeners_configuration_test.yaml
charts/hivemq-platform/tests/services/hivemq_control_center_services_test.yaml
charts/hivemq-platform/tests/services/hivemq_metrics_services_test.yaml
charts/hivemq-platform/tests/services/hivemq_rest_api_services_test.yaml
charts/hivemq-platform/tests/services/hivemq_services_test.yaml
charts/hivemq-platform/values.schema.json
charts/hivemq-platform/values.yaml

https://hivemq.kanbanize.com/ctrl_board/22/cards/28004/details/

Add external traffic policy to HiveMQ Platform services

---

charts/hivemq-platform/templates/_helpers.tpl
charts/hivemq-platform/templates/hivemq-configuration.yml
charts/hivemq-platform/templates/hivemq-custom-resource.yml
charts/hivemq-platform/templates/hivemq-license.yml
charts/hivemq-platform/tests/configuration/configmap/hivemq_configuration_test.yaml
charts/hivemq-platform/tests/configuration/secret/hivemq_configuration_test.yaml
charts/hivemq-platform/tests/hivemq_platform_test.yaml
charts/hivemq-platform/tests/licenses/hivemq_additional_broker_license_test.yaml
charts/hivemq-platform/tests/licenses/hivemq_datahub_license_test.yaml
charts/hivemq-platform/tests/licenses/hivemq_extensions_license_test.yaml
charts/hivemq-platform/tests/licenses/hivemq_license_test.yaml
charts/hivemq-platform/values.schema.json
charts/hivemq-platform/values.yaml

https://hivemq.kanbanize.com/ctrl_board/22/cards/28888/details/
_Implementation notes_: We cannot use an auto detect mechanism here to check whether the data passed in the value is actually Base64 encoded or not, due to the use of `overrideLicense` which is always in cleared text. Right now, if customer provides the `data` that one has to be Base64 encoded, but when using the `overrideLicense` that has to be in cleared text as per the license file itself.
So in an auto discovery mechanism, when using the `overrideLicense` value it will always be using the `data` field in the Secret no matter what, instead of the `stringData`

Custom annotations and labels for all platform resources along with `stringData` in License Secret

---

.github/workflows/release.yml
.gitignore
github-release-note-updater/build.gradle.kts
github-release-note-updater/gradle/libs.versions.toml
github-release-note-updater/src/main/java/com/hivemq/release/Chart.java
github-release-note-updater/src/main/java/com/hivemq/release/GitHubReleaseNotesUpdater.java
github-release-note-updater/src/main/java/com/hivemq/release/IndexFile.java
release/update-github-release-notes.sh

https://hivemq.kanbanize.com/ctrl_board/22/cards/29898/details/
We need to fix this, otherwise the release notes will not be updated if just the Chart is released for `hivemq-edge` without bumping the `appVersion` as well.
This also fixes the race condition between updating the `index.yaml` by the chart releaser, which triggers a deployment of the GitHub page that is used for our Helm repository, and using the Helm repository information to update the GitHub release notes. The solution is to download the updated `index.yaml` file instead of using the `helm repo update` (that needs the GitHub pages deployment to be done).

Fix race condition in release notes updates and do not check previous appVersion for simple release note generation (used by hivemq-edge)
